mods.extendedcrafting.TableCrafting.addShaped("sculk", 0, <item:minecraft:sculk>, [
	[<item:minecraft:sculk_vein>, <item:minecraft:sculk_vein>, <item:minecraft:sculk_vein>], 
	[<item:minecraft:sculk_vein>, <item:minecraft:sculk_vein>, <item:minecraft:sculk_vein>], 
	[<item:minecraft:sculk_vein>, <item:minecraft:sculk_vein>, <item:minecraft:sculk_vein>]
]);
recipes.remove(<item:cqcore:mechanical_core>);
mods.extendedcrafting.TableCrafting.addShaped("mechanical_core", 1, <item:cqcore:mechanical_core>, [
	[<item:ars_nouveau:abjuration_essence>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:advanced_catalyst>], 
	[<item:ad_astra:desh_plate>, <item:mekanism:advanced_control_circuit>, <item:ad_astra:desh_plate>], 
	[<item:extendedcrafting:advanced_catalyst>, <item:extendedcrafting:redstone_ingot>, <item:ars_nouveau:abjuration_essence>]
]);
mods.extendedcrafting.TableCrafting.addShaped("boss_item", 0, <item:cqcore:boss_item>, [
	[<item:spirit:soul_crystal>, <item:extendedcrafting:nether_star_block>, <item:deeperdarker:heart_of_the_deep>, <item:minecraft:dragon_egg>, <item:spirit:soul_crystal>], 
	[<item:cataclysm:monstrous_horn>, <item:twilightforest:ur_ghast_trophy>, <item:twilightforest:alpha_yeti_trophy>, <item:twilightforest:quest_ram_trophy>, <item:cataclysm:music_disc_ignis>], 
	[<item:botania:life_essence>, <item:twilightforest:lich_trophy>, <item:twilightforest:knight_phantom_trophy>, <item:twilightforest:hydra_trophy>, <item:cataclysm:music_disc_the_harbinger>], 
	[<item:cataclysm:void_core>, <item:twilightforest:naga_trophy>, <item:twilightforest:minoshroom_trophy>, <item:twilightforest:snow_queen_trophy>, <item:cataclysm:music_disc_ender_guardian>], 
	[<item:spirit:soul_crystal>, <item:hostilenetworks:data_model>.withTag({data_model: {id: "hostilenetworks:wither"}}), <item:hostilenetworks:data_model>.withTag({data_model: {id: "hostilenetworks:elder_guardian"}}), <item:hostilenetworks:data_model>.withTag({data_model: {id: "hostilenetworks:ender_dragon"}}), <item:spirit:soul_crystal>]
]);
mods.extendedcrafting.TableCrafting.addShapeless("the_ultimate_ingot", 0, <item:extendedcrafting:the_ultimate_ingot>, [
	<item:upgradednetherite:poison_upgraded_netherite_ingot>, <item:upgradednetherite:echo_upgraded_netherite_ingot>, <item:upgradednetherite:phantom_upgraded_netherite_ingot>, <item:upgradednetherite:feather_upgraded_netherite_ingot>, <item:upgradednetherite:water_upgraded_netherite_ingot>, <item:upgradednetherite:wither_upgraded_netherite_ingot>, <item:upgradednetherite:ender_upgraded_netherite_ingot>, <item:upgradednetherite:gold_upgraded_netherite_ingot>, <item:upgradednetherite:fire_upgraded_netherite_ingot>, <item:upgradednetherite:corrupt_upgraded_netherite_ingot>, <item:twilightforest:knightmetal_ingot>, <item:twilightforest:fiery_ingot>, <item:twilightforest:ironwood_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:gold_ingot>, <item:minecraft:copper_ingot>, <item:minecraft:iron_ingot>, <item:botania:manasteel_ingot>, <item:botania:terrasteel_ingot>, <item:botania:elementium_ingot>, <item:botania:gaia_ingot>, <item:cataclysm:witherite_ingot>, <item:cataclysm:ignitium_ingot>, <item:mysticalagriculture:prosperity_ingot>, <item:mysticalagriculture:inferium_ingot>, <item:mysticalagriculture:prudentium_ingot>, <item:mekanism:ingot_refined_glowstone>, <item:mekanism:ingot_steel>, <item:mekanism:ingot_osmium>, <item:mekanism:ingot_tin>, <item:mekanism:ingot_lead>, <item:mekanism:ingot_uranium>, <item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:enhanced_redstone_ingot>, <item:mysticalagriculture:supremium_ingot>, <item:mysticalagriculture:awakened_supremium_ingot>, <item:mysticalagriculture:soulium_ingot>, <item:mysticalagradditions:insanium_ingot>, <item:aquaculture:neptunium_ingot>, <item:mekanism:ingot_bronze>, <item:mekanism:ingot_refined_obsidian>, <item:mysticalagriculture:tertium_ingot>, <item:mysticalagriculture:imperium_ingot>, <item:ad_astra:calorite_ingot>, <item:ad_astra:ostrum_ingot>, <item:ad_astra:desh_ingot>, <item:ad_astra:steel_ingot>, <item:pneumaticcraft:ingot_iron_compressed>, <item:spirit:soul_steel_ingot>, <item:industrialforegoing:pink_slime_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:enhanced_ender_ingot>, <item:extendedcrafting:ender_ingot>
]);

mods.extendedcrafting.TableCrafting.addShapeless("meaty_meat", 0, <item:cqcore:meaty_meat>, [
	<item:nethersdelight:hoglin_loin>, <item:nethersdelight:hoglin_ear>, <item:farmersdelight:smoked_ham>, <item:farmersdelight:ham>, <item:farmersdelight:cooked_salmon_slice>, <item:farmersdelight:mutton_chops>, <item:delightful:venison_chops>, <item:twilightforest:cooked_venison>, <item:farmersdelight:cod_slice>, <item:farmersdelight:beef_patty>, <item:farmersdelight:minced_beef>, <item:twilightforest:raw_meef>, <item:twilightforest:hydra_chop>, <item:delightful:cooked_venison_chops>, <item:artifacts:eternal_steak>, <item:artifacts:everlasting_beef>, <item:twilightforest:raw_venison>, <item:farmersdelight:cooked_mutton_chops>, <item:farmersdelight:bacon>, <item:nethersdelight:strider_slice>, <item:nethersdelight:hoglin_sirloin>, <item:minecraft:chicken>, <item:minecraft:cooked_rabbit>, <item:minecraft:rabbit>, <item:farmersdelight:cooked_chicken_cuts>, <item:farmersdelight:cooked_bacon>, <item:minecraft:cooked_beef>, <item:farmersdelight:salmon_slice>, <item:minecraft:cooked_porkchop>, <item:minecraft:porkchop>, <item:farmersdelight:chicken_cuts>, <item:minecraft:beef>, <item:farmersdelight:cooked_cod_slice>, <item:minecraft:cooked_chicken>, <item:croptopia:cooked_bacon>, <item:croptopia:pepperoni>, <item:croptopia:beef_jerky>, <item:croptopia:pork_jerky>, <item:croptopia:fried_frog_legs>, <item:croptopia:frog_legs>, <item:croptopia:ground_pork>, <item:croptopia:bacon>
]);

mods.extendedcrafting.TableCrafting.addShapeless("vegaetabley_vegetables", 0, <item:cqcore:vegaetabley_vegetables>, [
	<item:croptopia:blackbean>, <item:farmersdelight:cabbage_leaf>, <item:croptopia:avocado>, <item:farmersdelight:onion>, <item:farmersdelight:cabbage>, <item:croptopia:sea_lettuce>, <item:nethersdelight:propelpearl>, <item:croptopia:broccoli>, <item:croptopia:barley>, <item:croptopia:asparagus>, <item:croptopia:cucumber>, <item:croptopia:cabbage>, <item:croptopia:yam>, <item:minecraft:dried_kelp>, <item:delightful:cactus_flesh>, <item:delightful:cactus_steak>, <item:croptopia:rhubarb>, <item:croptopia:cauliflower>, <item:croptopia:kale_chips>, <item:croptopia:potato_chips>, <item:croptopia:celery>, <item:croptopia:chile_pepper>, <item:croptopia:coffee_beans>, <item:croptopia:baked_yam>, <item:croptopia:baked_sweet_potato>, <item:croptopia:cabbage_roll>, <item:minecraft:carrot>, <item:croptopia:peanut_butter_with_celery>, <item:minecraft:mutton>, <item:minecraft:cooked_mutton>, <item:minecraft:beetroot>, <item:croptopia:roasted_asparagus>, <item:croptopia:roasted_radishes>, <item:croptopia:stuffed_artichoke>, <item:croptopia:walnut>, <item:croptopia:basil>, <item:croptopia:zucchini>, <item:croptopia:almond>, <item:croptopia:pecan>, <item:duckling:raw_duck>, <item:duckling:cooked_duck>, <item:croptopia:artichoke>, <item:croptopia:corn>, <item:croptopia:bellpepper>, <item:croptopia:nutmeg>, <item:croptopia:eggplant>, <item:croptopia:rice>, <item:croptopia:radish>, <item:croptopia:squash>, <item:croptopia:sweetpotato>, <item:croptopia:tea_leaves>, <item:croptopia:turmeric>, <item:croptopia:turnip>, <item:croptopia:vanilla>, <item:croptopia:cashew>, <item:croptopia:rutabaga>, <item:croptopia:soybean>, <item:croptopia:spinach>, <item:croptopia:pepper>, <item:croptopia:peanut>, <item:croptopia:onion>, <item:croptopia:olive>, <item:croptopia:oat>, <item:croptopia:mustard>, <item:croptopia:garlic>, <item:croptopia:ginger>, <item:croptopia:kale>, <item:croptopia:hops>, <item:croptopia:greenbean>, <item:croptopia:leek>, <item:croptopia:lettuce>, <item:croptopia:greenonion>
]);

mods.extendedcrafting.TableCrafting.addShapeless("sweet_treats_treat", 0, <item:cqcore:sweet_treats_treat>, [
	<item:pneumaticcraft:sourdough_bread>, <item:croptopia:corn_bread>, <item:croptopia:banana_nut_bread>, <item:vinery:crusty_bread>, <item:vinery:milk_bread>, <item:reliquary:glowing_bread>, <item:vinery:bread_slice>, <item:vinery:chocolate_bread>, <item:minecraft:bread>, <item:minecraft:cookie>, <item:minecraft:cake>, <item:cyclic:inventory_cake>, <item:botania:mana_cookie>, <item:minecraft:baked_potato>, <item:minecraft:potato>, <item:minecraft:pumpkin_pie>, <item:vinery:apple_pie>, <item:delightful:source_berry_pie_slice>, <item:ars_nouveau:source_berry_roll>, <item:ars_nouveau:source_berry_pie>, <item:vinery:apple_pie_slice>, <item:vinery:apple_cupcake>, <item:vinery:donut>, <item:vinery:toast>, <item:twilightforest:maze_wafer>, <item:twilightforest:experiment_115>, <item:delightful:rock_candy>, <item:delightful:marshmallow_stick>, <item:farmersdelight:melon_popsicle>, <item:delightful:cooked_marshmallow_stick>, <item:croptopia:doughnut>, <item:croptopia:chocolate>, <item:croptopia:rhubarb_pie>, <item:croptopia:pecan_pie>, <item:croptopia:cherry_pie>, <item:croptopia:apple_pie>, <item:croptopia:caramel>, <item:duckling:holiday_fruit_cake>, <item:nethersdelight:magma_gelatin>, <item:croptopia:vanilla_ice_cream>, <item:delightful:smore>, <item:croptopia:tortilla>, <item:farmersdelight:apple_pie_slice>, <item:farmersdelight:sweet_berry_cheesecake_slice>, <item:farmersdelight:chocolate_pie_slice>, <item:farmersdelight:sweet_berry_cookie>, <item:farmersdelight:honey_cookie>, <item:farmersdelight:apple_pie>, <item:farmersdelight:sweet_berry_cheesecake>, <item:farmersdelight:chocolate_pie>, <item:farmersdelight:pie_crust>, <item:farmersdelight:cake_slice>, <item:croptopia:macaron>, <item:croptopia:french_fries>, <item:croptopia:sweet_potato_fries>, <item:croptopia:trifle>, <item:croptopia:tofu>, <item:croptopia:butter>, <item:croptopia:cheese>, <item:ad_astra:cheese>, <item:croptopia:sticky_toffee_pudding>, <item:croptopia:treacle_tart>, <item:croptopia:pumpkin_bars>, <item:croptopia:candied_nuts>, <item:croptopia:candy_corn>, <item:croptopia:cheese_cake>, <item:croptopia:brownies>, <item:croptopia:banana_cream_pie>, <item:croptopia:snicker_doodle>, <item:croptopia:scones>, <item:croptopia:figgy_pudding>, <item:croptopia:churros>, <item:croptopia:raisin_oatmeal_cookie>, <item:croptopia:nutty_cookie>, <item:croptopia:trail_mix>, <item:delightful:salmonberry_gummy>, <item:delightful:salmonberry_pie_slice>, <item:delightful:pumpkin_pie_slice>, <item:farmersdelight:glow_berry_custard>, <item:croptopia:meringue>, <item:croptopia:lemon_coconut_bar>
]);

mods.extendedcrafting.TableCrafting.addShapeless("the_stew_of_stews", 0, <item:cqcore:the_stew_of_stews>, [
	<item:farmersdelight:noodle_soup>, <item:farmersdelight:baked_cod_stew>, <item:croptopia:baked_beans>, <item:croptopia:salsa>, <item:croptopia:caesar_salad>, <item:farmersdelight:chicken_soup>, <item:farmersdelight:pumpkin_soup>, <item:farmersdelight:fried_rice>, <item:farmersdelight:fish_stew>, <item:farmersdelight:mixed_salad>, <item:farmersdelight:fruit_salad>, <item:croptopia:popcorn>, <item:vinery:applesauce>, <item:croptopia:artichoke_dip>, <item:farmersdelight:cooked_rice>, <item:farmersdelight:bone_broth>, <item:farmersdelight:beef_stew>, <item:farmersdelight:vegetable_soup>, <item:croptopia:onion_rings>, <item:croptopia:cucumber_salad>, <item:croptopia:carnitas>, <item:croptopia:crema>, <item:croptopia:refried_beans>, <item:croptopia:steamed_rice>, <item:croptopia:mango_ice_cream>, <item:croptopia:pecan_ice_cream>, <item:croptopia:strawberry_ice_cream>, <item:croptopia:rum_raisin_ice_cream>, <item:croptopia:cashew_chicken>, <item:croptopia:chicken_and_noodles>, <item:croptopia:chicken_and_dumplings>, <item:croptopia:tofu_and_dumplings>, <item:croptopia:spaghetti_squash>, <item:croptopia:saucy_chips>, <item:croptopia:yoghurt>, <item:croptopia:leek_soup>, <item:croptopia:oatmeal>, <item:croptopia:pork_and_beans>, <item:croptopia:veggie_salad>, <item:croptopia:fruit_salad>, <item:croptopia:leafy_salad>, <item:croptopia:chicken_and_rice>, <item:croptopia:ajvar>, <item:farmersdelight:stuffed_pumpkin>, <item:croptopia:beef_stew>, <item:farmersdelight:dog_food>, <item:croptopia:steamed_broccoli>, <item:croptopia:steamed_green_beans>, <item:croptopia:pumpkin_soup>, <item:croptopia:borscht>, <item:croptopia:goulash>, <item:delightful:sinigang>, <item:delightful:coconut_curry>, <item:delightful:field_salad>, <item:croptopia:ratatouille>, <item:croptopia:potato_soup>, <item:croptopia:chocolate_ice_cream>, <item:croptopia:nether_wart_stew>, <item:croptopia:kiwi_sorbet>, <item:croptopia:beetroot_salad>, <item:croptopia:buttered_green_beans>
]);

mods.extendedcrafting.TableCrafting.addShapeless("idk_im_running_out_of_names_for_food", 0, <item:cqcore:idk_im_running_out_of_names_for_food>, [
	<item:croptopia:toast>, <item:croptopia:toast_sandwich>, <item:croptopia:hashed_brown>, <item:croptopia:roasted_sunflower_seeds>, <item:croptopia:baked_crepes>, <item:croptopia:anchovy_pizza>, <item:croptopia:quiche>, <item:croptopia:sausage>, <item:croptopia:sunny_side_eggs>, <item:croptopia:sweet_crepes>, <item:croptopia:protein_bar>, <item:croptopia:nougat>, <item:croptopia:scrambled_eggs>, <item:croptopia:buttered_toast>, <item:croptopia:toast_with_jam>, <item:croptopia:ham_sandwich>, <item:croptopia:peanut_butter_and_jam>, <item:croptopia:blt>, <item:croptopia:grilled_cheese>, <item:croptopia:tuna_sandwich>, <item:croptopia:hamburger>, <item:croptopia:tofuburger>, <item:croptopia:pizza>, <item:croptopia:supreme_pizza>, <item:croptopia:cheese_pizza>, <item:croptopia:pineapple_pepperoni_pizza>, <item:croptopia:lemon_chicken>, <item:croptopia:fried_chicken>, <item:croptopia:mashed_potatoes>, <item:croptopia:tuna_roll>, <item:croptopia:cinnamon_roll>, <item:croptopia:the_big_breakfast>, <item:croptopia:croque_madame>, <item:croptopia:taco>, <item:croptopia:sushi>, <item:croptopia:egg_roll>, <item:croptopia:croque_monsieur>, <item:croptopia:dauphine_potatoes>, <item:delightful:animal_fat>, <item:croptopia:roasted_pumpkin_seeds>, <item:croptopia:eggplant_parmesan>, <item:croptopia:avocado_toast>, <item:croptopia:ajvar_toast>, <item:croptopia:shepherds_pie>, <item:croptopia:beef_wellington>, <item:croptopia:almond_brittle>, <item:croptopia:fish_and_chips>, <item:croptopia:cornish_pasty>, <item:croptopia:burrito>, <item:croptopia:tostada>, <item:croptopia:corn_husk>, <item:croptopia:chimichanga>, <item:croptopia:fajitas>, <item:croptopia:enchilada>, <item:croptopia:quesadilla>, <item:croptopia:tamales>, <item:croptopia:tres_leche_cake>, <item:croptopia:stuffed_poblanos>, <item:croptopia:chili_relleno>
]);

mods.extendedcrafting.TableCrafting.addShapeless("meal_of_meals", 0, <item:cqcore:meal_of_meals>, [
	<item:nethersdelight:strider_moss_stew>, <item:farmersdelight:grilled_salmon>, <item:nethersdelight:plate_of_stuffed_hoglin_snout>, <item:nethersdelight:plate_of_stuffed_hoglin_ham>, <item:pneumaticcraft:cod_n_chips>, <item:delightful:nut_butter_and_jelly_sandwich>, <item:farmersdelight:shepherds_pie>, <item:delightful:cheeseburger>, <item:delightful:deluxe_cheeseburger>, <item:farmersdelight:squid_ink_pasta>, <item:farmersdelight:ratatouille>, <item:farmersdelight:steak_and_potatoes>, <item:farmersdelight:vegetable_noodles>, <item:delightful:crab_rangoon>, <item:delightful:honey_glazed_walnut>, <item:farmersdelight:honey_glazed_ham>, <item:farmersdelight:mushroom_rice>, <item:minecraft:rabbit_stew>, <item:farmersdelight:pasta_with_meatballs>, <item:minecraft:mushroom_stew>, <item:farmersdelight:pasta_with_mutton_chop>, <item:farmersdelight:fried_egg>, <item:nethersdelight:nether_skewer>, <item:nethersdelight:plate_of_stuffed_hoglin_roast>, <item:farmersdelight:tomato_sauce>, <item:croptopia:stir_fry>, <item:croptopia:beef_stir_fry>, <item:minecraft:beetroot_soup>, <item:croptopia:roasted_turnips>, <item:croptopia:roasted_squash>, <item:croptopia:rhubarb_crisp>, <item:croptopia:grilled_eggplant>, <item:croptopia:candied_kumquats>, <item:croptopia:fruit_cake>, <item:croptopia:cheesy_asparagus>, <item:delightful:salmonberries>, <item:croptopia:roasted_nuts>, <item:farmersdelight:roasted_mutton_chops>, <item:farmersdelight:mutton_wrap>, <item:farmersdelight:kelp_roll_slice>, <item:farmersdelight:kelp_roll>, <item:farmersdelight:cabbage_rolls>, <item:farmersdelight:cod_roll>, <item:farmersdelight:bacon_and_eggs>, <item:nethersdelight:grilled_strider>, <item:farmersdelight:dumplings>, <item:farmersdelight:stuffed_potato>, <item:farmersdelight:bacon_sandwich>, <item:farmersdelight:chicken_sandwich>, <item:farmersdelight:egg_sandwich>, <item:farmersdelight:barbecue_stick>, <item:farmersdelight:hamburger>, <item:farmersdelight:salmon_roll>, <item:farmersdelight:roast_chicken>
]);

mods.extendedcrafting.TableCrafting.addShapeless("probably_poisonous_bottle_of_everything", 0, <item:cqcore:probably_poisonous_bottle_of_everything>, [
	<item:vinery:jellie_wine>, <item:vinery:aegis_wine>, <item:vinery:apple_wine>, <item:vinery:solaris_wine>, <item:vinery:kelp_cider>, <item:vinery:chenet_wine>, <item:vinery:apple_juice>, <item:vinery:white_grapejuice_wine_bottle>, <item:vinery:red_grapejuice_wine_bottle>, <item:vinery:wine_bottle>, <item:vinery:cherry_wine>, <item:vinery:bolvar_wine>, <item:vinery:noir_wine>, <item:vinery:mellohi_wine>, <item:vinery:clark_wine>, <item:vinery:king_danis_wine>, <item:vinery:apple_cider>, <item:farmersdelight:melon_juice>, <item:delightful:prickly_pear_juice>, <item:delightful:berry_matcha_latte>, <item:delightful:jelly_bottle>, <item:delightful:glow_jelly_bottle>, <item:delightful:nut_butter_bottle>, <item:farmersdelight:hot_cocoa>, <item:farmersdelight:apple_cider>, <item:croptopia:peanut_butter>, <item:croptopia:banana_smoothie>, <item:croptopia:strawberry_jam>, <item:croptopia:raspberry_jam>, <item:croptopia:peach_jam>, <item:croptopia:grape_jam>, <item:croptopia:orange_juice>, <item:croptopia:pineapple_juice>, <item:croptopia:saguaro_juice>, <item:croptopia:tomato_juice>, <item:croptopia:elderberry_jam>, <item:croptopia:melon_juice>, <item:croptopia:grape_juice>, <item:croptopia:cherry_jam>, <item:croptopia:blueberry_jam>, <item:croptopia:cranberry_juice>, <item:croptopia:apple_juice>, <item:croptopia:blackberry_jam>, <item:croptopia:apricot_jam>, <item:croptopia:strawberry_smoothie>, <item:croptopia:chocolate_milkshake>, <item:croptopia:beer>, <item:croptopia:soy_milk>, <item:croptopia:lemonade>, <item:croptopia:kale_smoothie>, <item:croptopia:coffee>, <item:croptopia:pumpkin_spice_latte>, <item:croptopia:rum>, <item:croptopia:fruit_smoothie>, <item:croptopia:wine>, <item:croptopia:mead>, <item:croptopia:limeade>, <item:delightful:lavender_tea>, <item:delightful:azalea_tea>, <item:croptopia:yam_jam>, <item:croptopia:horchata>, <item:croptopia:eton_mess>, <item:croptopia:tea>, <item:minecraft:honey_bottle>
]);

mods.extendedcrafting.TableCrafting.addShapeless("the_everyfood_1", 0, <item:cqcore:the_everyfood_1>, [
	<item:croptopia:plum>, <item:croptopia:persimmon>, <item:croptopia:pear>, <item:croptopia:peach>, <item:croptopia:orange>, <item:croptopia:nectarine>, <item:croptopia:mango>, <item:croptopia:lime>, <item:croptopia:lemon>, <item:twilightforest:torchberries>, <item:cyclic:chorus_spectral>, <item:cyclic:chorus_flight>, <item:minecraft:apple>, <item:ars_nouveau:source_berry>, <item:minecraft:golden_apple>, <item:ars_nouveau:mendosteen_pod>, <item:ars_nouveau:bastion_pod>, <item:minecraft:chorus_fruit>, <item:minecraft:sweet_berries>, <item:minecraft:glow_berries>, <item:quark:ancient_fruit>, <item:minecraft:melon_slice>, <item:minecraft:enchanted_golden_apple>, <item:cyclic:apple_ender>, <item:cyclic:apple_emerald>, <item:cyclic:apple_diamond>, <item:cyclic:apple_honey>, <item:cyclic:apple_chorus>, <item:cyclic:apple_bone>, <item:mysticalagradditions:tertium_apple>, <item:mysticalagradditions:prudentium_apple>, <item:mysticalagradditions:inferium_apple>, <item:cyclic:apple_chocolate>, <item:cyclic:apple_lofty_stature>, <item:cyclic:apple_iron>, <item:cyclic:apple_lapis>, <item:cyclic:apple_prismarine>, <item:mysticalagradditions:imperium_apple>, <item:mysticalagradditions:supremium_apple>, <item:mysticalagradditions:insanium_apple>, <item:croptopia:grape>, <item:croptopia:elderberry>, <item:croptopia:coconut>, <item:croptopia:banana>, <item:croptopia:apricot>, <item:croptopia:date>, <item:croptopia:dragonfruit>, <item:croptopia:fig>, <item:croptopia:grapefruit>, <item:croptopia:tomato>, <item:croptopia:tomatillo>, <item:croptopia:honeydew>, <item:croptopia:currant>, <item:croptopia:cranberry>, <item:croptopia:cantaloupe>, <item:vinery:apple_mash>, <item:vinery:white_grape>, <item:vinery:red_grape>, <item:croptopia:blueberry>, <item:vinery:cherry>, <item:croptopia:cherry>, <item:croptopia:kumquat>, <item:croptopia:strawberry>, <item:croptopia:pineapple>, <item:croptopia:raspberry>, <item:croptopia:saguaro>, <item:croptopia:kiwi>, <item:farmersdelight:tomato>, <item:croptopia:starfruit>, <item:croptopia:blackberry>, <item:farmersdelight:pumpkin_slice>, <item:delightful:cantaloupe_slice>, <item:croptopia:raisins>, <item:delightful:acorn>
]);

mods.extendedcrafting.TableCrafting.addShapeless("fishy_fish", 0, <item:cqcore:fishy_fish>, [
	<item:minecraft:tropical_fish>, <item:minecraft:pufferfish>, <item:minecraft:cooked_cod>, <item:minecraft:cod>, <item:minecraft:salmon>, <item:aquaculture:algae>, <item:aquaculture:fish_fillet_raw>, <item:aquaculture:fish_fillet_cooked>, <item:twilightforest:meef_stroganoff>, <item:aquaculture:turtle_soup>, <item:croptopia:sushi>, <item:aquaculture:sushi>, <item:aquaculture:atlantic_halibut>, <item:aquaculture:atlantic_herring>, <item:aquaculture:pacific_halibut>, <item:aquaculture:blackfish>, <item:aquaculture:atlantic_cod>, <item:aquaculture:pink_salmon>, <item:aquaculture:pollock>, <item:aquaculture:rainbow_trout>, <item:aquaculture:boulti>, <item:aquaculture:capitaine>, <item:aquaculture:synodontis>, <item:aquaculture:smallmouth_bass>, <item:aquaculture:bluegill>, <item:aquaculture:brown_trout>, <item:aquaculture:bayad>, <item:aquaculture:carp>, <item:aquaculture:catfish>, <item:aquaculture:gar>, <item:aquaculture:minnow>.withTag({Damage: 0 as int}), <item:aquaculture:muskellunge>, <item:aquaculture:perch>, <item:aquaculture:arapaima>, <item:aquaculture:piranha>, <item:aquaculture:tambaqui>, <item:aquaculture:tuna>, <item:aquaculture:red_grouper>, <item:aquaculture:jellyfish>, <item:aquaculture:red_shrooma>, <item:aquaculture:brown_shrooma>, <item:croptopia:crab>, <item:croptopia:glowing_calamari>, <item:pneumaticcraft:chips>, <item:pneumaticcraft:salmon_tempura>, <item:quark:crab_leg>, <item:quark:cooked_crab_leg>, <item:minecraft:cooked_salmon>, <item:croptopia:roe>, <item:croptopia:oyster>, <item:croptopia:clam>, <item:croptopia:calamari>, <item:croptopia:anchovy>, <item:croptopia:tuna>, <item:croptopia:cooked_tuna>, <item:croptopia:cooked_shrimp>, <item:croptopia:shrimp>, <item:croptopia:cooked_anchovy>, <item:croptopia:cooked_calamari>, <item:croptopia:steamed_crab>, <item:croptopia:deep_fried_shrimp>, <item:croptopia:grilled_oysters>, <item:croptopia:crab_legs>, <item:croptopia:fried_calamari>, <item:croptopia:steamed_clams>
]);

mods.extendedcrafting.TableCrafting.addShapeless("the_ultimate_ultimate", 0, <item:cqcore:the_ultimate_ultimate>, [
	<item:extendedcrafting:ultimate_singularity>, <item:powah:energy_cell_nitro>, <item:ad_astra:jet_suit>.withTag({BotariumData: {},}), <item:extendedcrafting:the_ultimate_catalyst>, <item:pipez:ultimate_upgrade>, <item:ironjetpacks:ultimate_coil>, <item:mekanism:ultimate_tier_installer>, <item:mekanism:ultimate_control_circuit>, <item:mekanism:ultimate_universal_cable>, <item:deeperdarker:soul_elytra>, <item:a_man_with_plushies:companion_block_plushie>, <item:ae2:spatial_anchor>, <item:aquaculture:neptunium_fishing_rod>, <item:ironjetpacks:jetpack>.withTag({Id: "ironjetpacks:emerald", Throttle: 1.0 as double}), <item:lootr:trophy>, <item:botania:floating_dandelifeon>, <item:pneumaticcraft:guard_drone>, <item:extendedcrafting:ultimate_auto_table>, <item:ironfurnaces:million_furnace>.withTag({display: {Name: "{\"extra\":[{\"color\":\"green\",\"text\":\"R\"},{\"color\":\"aqua\",\"text\":\"a\"},{\"color\":\"light_purple\",\"text\":\"i\"},{\"color\":\"blue\",\"text\":\"n\"},{\"color\":\"blue\",\"text\":\"b\"},{\"color\":\"green\",\"text\":\"o\"},{\"color\":\"green\",\"text\":\"w\"},{\"color\":\"red\",\"text\":\" \"},{\"color\":\"green\",\"text\":\"F\"},{\"color\":\"green\",\"text\":\"u\"},{\"color\":\"red\",\"text\":\"r\"},{\"color\":\"light_purple\",\"text\":\"n\"},{\"color\":\"green\",\"text\":\"a\"},{\"color\":\"yellow\",\"text\":\"c\"},{\"color\":\"green\",\"text\":\"e\"}],\"text\":\"\"}"}}), <item:powah:thermo_generator_nitro>, <item:sophisticatedbackpacks:netherite_backpack>, <item:easy_villagers:villager>, <item:ae2:256k_crafting_storage>, <item:storagedrawers:emerald_storage_upgrade>, <item:ars_nouveau:archmage_spell_book>, <item:compactmachines:machine_giant>, <item:mininggadgets:mininggadget>.withTag({energy: 1000000.0 as double}), <item:mysticalagradditions:insanium_essence>, <item:mekanism:ultimate_compressing_factory>, <item:mekanism:ultimate_crushing_factory>, <item:mekanism:ultimate_infusing_factory>, <item:mekanism:ultimate_smelting_factory>, <item:mekanism:ultimate_enriching_factory>, <item:mekanism:ultimate_sawing_factory>, <item:mekanism:ultimate_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "256000000"}]}}), <item:mekanism:ultimate_injecting_factory>, <item:mekanism:ultimate_induction_provider>, <item:mekanism:ultimate_energy_cube>, <item:mekanism:ultimate_bin>, <item:mekanism:ultimate_induction_cell>, <item:mekanism:ultimate_purifying_factory>, <item:mekanism:ultimate_combining_factory>, <item:mekanism:ultimate_fluid_tank>, <item:trashcans:ultimate_trash_can>, <item:mekanism:ultimate_chemical_tank>, <item:mekanism:ultimate_mechanical_pipe>, <item:mekanism:ultimate_pressurized_tube>, <item:mekanism:ultimate_thermodynamic_conductor>, <item:mekanism:ultimate_logistical_transporter>, <item:ae2:fluix_smart_dense_cable>, <item:pipez:universal_pipe>
]);

mods.extendedcrafting.TableCrafting.addShaped("arscraftingstation", 0, <item:cqcore:compressed_ars_crafting_station>, [
	[<item:ars_nouveau:magebloom_fiber>, <item:ars_nouveau:source_gem>, <item:ars_nouveau:arcane_pedestal>, <item:ars_nouveau:source_gem>, <item:ars_nouveau:magebloom_fiber>], 
	[<item:ars_nouveau:source_gem>, <item:ars_nouveau:arcane_pedestal>, <item:ars_nouveau:enchanting_apparatus>, <item:ars_nouveau:arcane_pedestal>, <item:ars_nouveau:source_gem>], 
	[<item:ars_nouveau:arcane_pedestal>, <item:ars_nouveau:imbuement_chamber>, <item:ars_nouveau:source_berry>, <item:ars_nouveau:scribes_table>, <item:ars_nouveau:arcane_pedestal>], 
	[<item:ars_nouveau:source_gem>, <item:ars_nouveau:arcane_pedestal>, <item:ars_nouveau:arcane_core>, <item:ars_nouveau:arcane_pedestal>, <item:ars_nouveau:source_gem>], 
	[<item:ars_nouveau:magebloom_fiber>, <item:ars_nouveau:source_gem>, <item:ars_nouveau:arcane_pedestal>, <item:ars_nouveau:source_gem>, <item:ars_nouveau:magebloom_fiber>]
]);

mods.extendedcrafting.TableCrafting.addShaped("67b2c5f7-24f1-49c7-b63e-4471a2cc1089", 0, <item:projecte:alchemical_coal>, [
	[<item:minecraft:air>, <item:minecraft:coal>, <item:minecraft:air>], 
	[<item:minecraft:coal>, <item:cqcore:compressed_ars_crafting_station>, <item:minecraft:coal>], 
	[<item:minecraft:air>, <item:minecraft:coal>, <item:minecraft:air>]
]);

mods.extendedcrafting.TableCrafting.addShaped("a0960319-81dc-4bfa-a5ee-678395925641", 0, <item:projecte:mobius_fuel>, [
	[<item:minecraft:air>, <item:projecte:alchemical_coal>, <item:minecraft:air>], 
	[<item:projecte:alchemical_coal>, <item:cqcore:compressed_ars_crafting_station>, <item:projecte:alchemical_coal>], 
	[<item:minecraft:air>, <item:projecte:alchemical_coal>, <item:minecraft:air>]
]);

mods.extendedcrafting.TableCrafting.addShaped("5e5809b7-31af-4c08-97ea-7eba91db1970", 0, <item:projecte:aeternalis_fuel>, [
	[<item:minecraft:air>, <item:projecte:mobius_fuel>, <item:minecraft:air>], 
	[<item:projecte:mobius_fuel>, <item:cqcore:compressed_ars_crafting_station>, <item:projecte:mobius_fuel>], 
	[<item:minecraft:air>, <item:projecte:mobius_fuel>, <item:minecraft:air>]
]);

recipes.remove(<item:projecte:philosophers_stone>);
mods.extendedcrafting.TableCrafting.addShaped("6b6e1d32-1857-4f12-8057-81f6cd083ca4", 0, <item:projecte:philosophers_stone>, [
	[<item:botania:terrasteel_ingot>, <item:upgradednetherite:fire_essence>, <item:botania:terrasteel_ingot>], 
	[<item:cataclysm:ignitium_ingot>, <item:projecte:red_matter>, <item:cataclysm:ignitium_ingot>], 
	[<item:botania:terrasteel_ingot>, <item:upgradednetherite:fire_essence>, <item:botania:terrasteel_ingot>]
]);

recipes.remove(<item:cqcore:quantum_core>);
mods.extendedcrafting.TableCrafting.addShaped("cf655614-a1a2-4fff-9142-90bae1f01da5", 0, <item:cqcore:quantum_core>, [
	[<item:extendedcrafting:enhanced_redstone_catalyst>, <item:ae2:quantum_entangled_singularity>, <item:extendedcrafting:enhanced_ender_catalyst>], 
	[<item:mysticalagriculture:imperium_ingot>, <item:mekanism:advanced_induction_cell>, <item:minecraft:nether_star>], 
	[<item:extendedcrafting:enhanced_ender_catalyst>, <item:cqcore:mechanical_core>, <item:extendedcrafting:enhanced_redstone_catalyst>]
]);

mods.extendedcrafting.TableCrafting.addShaped("6d896d2f-a55a-4e8b-b14d-74c9e59064db", 0, <item:cqcore:creative_core>, [
	[<item:cqcore:probably_poisonous_bottle_of_everything>, <item:cqcore:meaty_meat>, <item:cqcore:idk_im_running_out_of_names_for_food>, <item:cqcore:the_stew_of_stews>, <item:cqcore:vegaetabley_vegetables>], 
	[<item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>, <item:cqcore:the_ultimate_ultimate>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>], 
	[<item:mekanism:superheated_sodium_bucket>, <item:cqcore:compressed_everything>, <item:cqcore:quantum_core>, <item:cqcore:boss_item>, <item:mekanismgenerators:fusion_fuel_bucket>], 
	[<item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>, <item:extendedcrafting:nether_star_block>], 
	[<item:cqcore:meal_of_meals>, <item:cqcore:fishy_fish>, <item:extendedcrafting:nether_star_block>, <item:cqcore:the_everyfood_1>, <item:cqcore:sweet_treats_treat>]
]);

recipes.remove(<item:storagedrawers:diamond_storage_upgrade>);
mods.extendedcrafting.TableCrafting.addShaped("c4bdf52f-226a-4186-816e-41ad3ceea810", 0, <item:storagedrawers:diamond_storage_upgrade>, [
	[<item:minecraft:stick>, <item:minecraft:stick>, <item:minecraft:stick>], 
	[<item:minecraft:diamond>, <item:storagedrawers:upgrade_template>, <item:minecraft:diamond>], 
	[<item:minecraft:stick>, <item:cqcore:mechanical_core>, <item:minecraft:stick>]
]);

recipes.remove(<item:mekanismgenerators:advanced_solar_generator>);
mods.extendedcrafting.TableCrafting.addShaped("449f29f0-d4f5-416a-a9ec-025c5f80def8", 0, <item:mekanismgenerators:advanced_solar_generator>, [
	[<item:mekanismgenerators:solar_generator>, <item:mekanism:alloy_infused>, <item:mekanismgenerators:solar_generator>], 
	[<item:mekanismgenerators:solar_generator>, <item:cqcore:mechanical_core>, <item:mekanismgenerators:solar_generator>], 
	[<item:minecraft:iron_ingot>, <item:minecraft:iron_ingot>, <item:minecraft:iron_ingot>]
]);


recipes.remove(<item:mekanismgenerators:wind_generator>);
mods.extendedcrafting.TableCrafting.addShaped("d9f090c7-642f-4225-87d4-5a8de4d4be58", 0, <item:mekanismgenerators:wind_generator>, [
	[<item:minecraft:air>, <item:mekanism:ingot_osmium>, <item:minecraft:air>], 
	[<item:mekanism:ingot_osmium>, <item:cqcore:mechanical_core>, <item:mekanism:ingot_osmium>], 
	[<item:mekanism:energy_tablet>, <item:mekanism:basic_control_circuit>, <item:mekanism:energy_tablet>]
]);


recipes.remove(<item:ironfurnaces:upgrade_netherite>);
recipes.remove(<item:ironfurnaces:netherite_furnace>);
mods.extendedcrafting.TableCrafting.addShaped("90f35388-f022-4e05-ba1b-9f155957b3b7", 0, <item:ironfurnaces:netherite_furnace>, [
	[<item:minecraft:netherite_ingot>, <item:minecraft:magma_cream>, <item:minecraft:netherite_ingot>], 
	[<item:minecraft:magma_cream>, <item:ironfurnaces:obsidian_furnace>, <item:minecraft:magma_cream>], 
	[<item:minecraft:netherite_ingot>, <item:cqcore:mechanical_core>, <item:minecraft:netherite_ingot>]
]);

recipes.remove(<item:extendedcrafting:ultimate_table>);
mods.extendedcrafting.TableCrafting.addShaped("34fc8d76-58fa-4cd3-be71-c21a7d00d9a6", 0, <item:extendedcrafting:ultimate_table>, [
	[<item:extendedcrafting:ultimate_component>, <item:extendedcrafting:ultimate_catalyst>, <item:extendedcrafting:ultimate_component>], 
	[<item:extendedcrafting:elite_table>, <item:cqcore:quantum_core>, <item:extendedcrafting:elite_table>], 
	[<item:extendedcrafting:ultimate_component>, <item:extendedcrafting:black_iron_slate>, <item:extendedcrafting:ultimate_component>]
]);

recipes.remove(<item:ae2:controller>);
mods.extendedcrafting.TableCrafting.addShaped("bbb43b38-1ddc-4426-8adb-cd9d098ad749", 0, <item:ae2:controller>, [
	[<item:ae2:smooth_sky_stone_block>, <item:ae2:certus_quartz_crystal>, <item:ae2:smooth_sky_stone_block>], 
	[<item:ae2:certus_quartz_crystal>, <item:ae2:engineering_processor>, <item:ae2:certus_quartz_crystal>], 
	[<item:ae2:smooth_sky_stone_block>, <item:cqcore:mechanical_core>, <item:ae2:smooth_sky_stone_block>]
]);


recipes.remove(<item:mekanism:enrichment_chamber>);
mods.extendedcrafting.TableCrafting.addShaped("7550caab-cef2-48d3-81fb-bfaf778da861", 0, <item:mekanism:enrichment_chamber>, [
	[<item:minecraft:redstone>, <item:mekanism:advanced_control_circuit>, <item:minecraft:redstone>], 
	[<item:minecraft:iron_ingot>, <item:mekanism:steel_casing>, <item:minecraft:iron_ingot>], 
	[<item:minecraft:redstone>, <item:cqcore:mechanical_core>, <item:minecraft:redstone>]
]);

recipes.remove(<item:extendedcrafting:compressor>);
mods.extendedcrafting.TableCrafting.addShaped("ac7e6418-272a-4a42-ab7f-dd3faddb879e", 0, <item:extendedcrafting:compressor>, [
	[<item:extendedcrafting:black_iron_ingot>, <item:extendedcrafting:elite_component>, <item:extendedcrafting:black_iron_ingot>], 
	[<item:extendedcrafting:elite_catalyst>, <item:extendedcrafting:frame>, <item:extendedcrafting:elite_catalyst>], 
	[<item:extendedcrafting:black_iron_ingot>, <item:cqcore:quantum_core>, <item:extendedcrafting:black_iron_ingot>]
]);

mods.extendedcrafting.TableCrafting.addShaped("1c1d2815-8f5f-4d9d-a70b-6601cf1b8ca0", 0, <item:cqcore:compressed_everything>, [
	[<item:simplemagnets:advancedmagnet>, <item:quark:ender_watcher>, <item:smallships:oak_brigg>, <item:enderstorage:ender_chest>, <item:swplanets:kyber_crystal>, <item:naturescompass:naturescompass>, <item:toolbelt:belt>, <item:tempad:tempad>, <item:ae2:singularity>], 
	[<item:chancecubes:chance_cube>, <item:buildinggadgets:gadget_building>.withTag({state: {serializer: "buildinggadgets:dummy_serializer", state: {Name: "minecraft:air"}, data: {}}}), <item:darkutils:vector_plate_ultra>, <item:upgradednetherite:ender_upgraded_netherite_horse_armor>, <item:cookingforblockheads:cow_jar>, <item:delightful:refined_obsidian_knife>, <item:torchmaster:megatorch>, <item:chipped:glassblower>, <item:industrialforegoing:straw>], 
	[<item:hostilenetworks:sim_chamber>, <item:compressium:diamond_3>, <item:cataclysm:the_incinerator>, <item:framedblocks:framed_flat_inv_double_slope_panel_corner>, <item:spirit:soul_cage>, <item:ironfurnaces:item_spooky>, <item:productivebees:wax>, <item:deeperdarker:stripped_echo_wood>, <item:cyclic:no_soliciting>], 
	[<item:cyclic:emerald_chestplate>, <item:a_man_with_plushies:creeper_plush>, <item:artifacts:charm_of_sinking>, <item:comforts:sleeping_bag_cyan>, <item:waystones:blue_sharestone>, <item:botanypots:cyan_glazed_terracotta_hopper_botany_pot>, <item:mininggadgets:upgrade_freezing>, <item:farmingforblockheads:market>, <item:ars_nouveau:scryers_oculus>], 
	[<item:mekanism:pellet_polonium>, <item:mekanism:atomic_disassembler>, <item:mysticalagriculture:supremium_hoe>, <item:twilightforest:naga_chestplate>, <item:nethersdelight:soul_compost>, <item:reliquary:holy_hand_grenade>, <item:croptopia:frying_pan>, <item:chiselsandbits:block_bit>.withTag({block_information: {state: "{\"Properties\":{\"axis\":\"y\"},\"Name\":\"minecraft:verdant_froglight\"}"}})], 
	[<item:powah:dry_ice>, <item:easy_piglins:piglin>, <item:botania:natura_pylon>, <item:elevatorid:elevator_red>, <item:domum_ornamentum:shingle_slab>.withTag({textureData: {"minecraft:block/oak_planks": "extendedcrafting:nether_star_block", "minecraft:block/dark_oak_planks": "extendedcrafting:nether_star_block", "minecraft:block/acacia_planks": "extendedcrafting:nether_star_block"}}), <item:pneumaticcraft:solar_cell>, <item:easy_villagers:breeder>, <item:storagedrawers:oak_half_drawers_4>, <item:fluxnetworks:flux_block>], 
	[<item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>, <item:mekanism:pellet_antimatter>], 
	[<item:industrialforegoing:mob_imprisonment_tool>.withTag({entity: "minecraft:piglin_brute"}), <item:pneumaticcraft:plastic_brick_light_blue>, <item:projecte:philosophers_stone>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>], 
	[<item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>, <item:minecraft:air>]
]);
